version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db
  app:
    container_name: app
    restart: on-failure
    build: .
    depends_on:
      - mongo
    environment:
      WAIT_HOSTS: mongo:27017