version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db
  app:
    container_name: chat-bot
    restart: on-failure
    build: .
    depends_on:
      - mongo
    command: ["./wait-for-it.sh", "mongo:27017", "--", "node", "index.js"]